version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: enoca
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sinan
      MYSQL_DATABASE: enoca
      MYSQL_USER: root
      MYSQL_PASSWORD: sinan
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
